name: maclo_golden
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.3
  - torchvision=0.18
  - torchaudio=2.3
  - cpuonly
  - numpy=1.26
  - scipy
  - pandas
  - scikit-learn
  - opencv
  - pillow
  - matplotlib
  - pyyaml
  - pip
  - pip:
      - einops
      - pydicom
